### ISSUE TITLE
Update required

### ISSUE THREAD

**Issue by Subject-4** [Falkirks/iControlU#4]
I use an All API Loader which makes old api plugin works, (i tested on some plugins) but when it tries to load this plugin, an error comes up and it crashes server
*CRASH DUMP*
PocketMine-MP Crash Dump Sat Jan 20 06:51:10 PST 2018

Error: Declaration of icontrolu\iControlU::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $cmd, $label, array $args) must be compatible with pocketmine\plugin\PluginBase::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $command, string $label, array $args): bool
File: iControlU_dev-4.phar/src/icontrolu/iControlU
Line: 21
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[12] use pocketmine\event\player\PlayerAnimationEvent;
[13] use pocketmine\event\player\PlayerChatEvent;
[14] use pocketmine\event\player\PlayerDropItemEvent;
[15] use pocketmine\event\player\PlayerMoveEvent;
[16] use pocketmine\event\player\PlayerQuitEvent;
[17] use pocketmine\network\mcpe\protocol\AnimatePacket;
[18] use pocketmine\Player;
[19] use pocketmine\plugin\PluginBase;
[20] 
[21] class iControlU extends PluginBase implements CommandExecutor, Listener{
[22]     public $b;
[23]     /** @var  ControlSession[] */
[24]     public $s;
[25]     /** @var  InventoryUpdateTask */
[26]     public $inv;
[27]     public function onEnable(){
[28]         $this->s = [];
[29]         $this->b = [];
[30]         $this->inv = new InventoryUpdateTask($this);
[31]         $this->getServer()->getScheduler()->scheduleRepeatingTask($this->inv, 5);

Backtrace:

PocketMine-MP version: 1.7dev #634 [Protocol 160; API 3.0.0-ALPHA10]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux mcpe1.netherbox.com 2.6.32-042stab120.18 #1 SMP Fri Jan 13 10:32:04 MSK 2017 x86_64
PHP Version: 7.2.0RC3
Zend version: 3.2.0-dev
OS : Linux, linux

Loaded plugins:
Cameraman 1.1.0-4 by ChalkPE for API(s) 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10
CustomAlerts 1.7.2-3 by EvolSoft for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10
EssentialsPE 2.0.0 by LegendsOfMCPE Team for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10
NoTP 1.0.6-3 by awzaw for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10
CustomSetting 1.0.1 by LeNick for API(s) 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10
WorldBorder 1 by CookieCode for API(s) 3.0.0, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11
MagicWE2 5.7.1 by XenialDan for API(s) 3.0.0-ALPHA10
PEXProtection 0.1.1 by RevivalPMMP for API(s) 3.0.0-ALPHA9, 3.0.0-ALPHA10
BasicHUD 1.0.6-3 by aliuly for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10
fireworks 1.0.2 by XenialDan for API(s) 3.0.0-ALPHA10
Alias 1.2.0 by ZacHack for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10
VoteReward 4.0.0-B1 by VMPE Development Team for API(s) 3.0.0-ALPHA9, 3.0.0-ALPHA10
XBL_PlayerList 1.1 by TheRealLinuzo for API(s) 3.0.0-ALPHA9, 3.0.0-ALPHA10
AntiSpam 1.3 by xBeastMode for API(s) 2.0.0, 3.0.0-ALPHA10
FormAPI 1.2.6 by VMPE Development Team for API(s) 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11
DevTools 1.12.8 by PocketMine Team for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10
MagicTelePortal 1.3.2-4 by aliuly for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10
MissedItems 1 by CookieCode for API(s) 3.0.0, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11
Sizer 2.2.0 by CapricornOfLynx for API(s) 3.0.0-ALPHA10
MultiWorld 1.3.3 by CzechPMDevs, GamakCZ for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10
TeaSpoon 1.0.0 by CortexPE for API(s) 3.0.0-ALPHA9, 3.0.0-ALPHA10
AntiDupe 5.0.0-B1 by StrafelessPvP for API(s) 3.0.0-ALPHA9, 3.0.0-ALPHA10
NoPvpFlight 1.2.6 by Array for API(s) 3.0.0, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10
PurePerms 1.4.1-3 by 64FF00 & ProjectInfinity for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10
Specter 0.4 by Falkirks for API(s) 3.0.0-ALPHA9, 3.0.0-ALPHA10
RandomEnchant 2.0.1 by XenialDan for API(s) 3.0.0-ALPHA10

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrdXAtz2ziS/isoOXWbTIm0Hn5qylvn2MrGu/ZYazmbqQ2nXBAJSYxJgkOQkpWp+e/X3QD4kpM4
mWTn7lKViYhHo7vR/XU3CM5vnTyMRWfU3+8f7O0fHx32uh2RZTLrjH7r5JsUujrju7Prq8nF5fhu
fHNzfdPpdmKhFF9g37nwI57xPJQJk3MW+jLJMxkVnhee6Z9vRiOZnMk45knwPJX+vcjjMBGe5+s2
zzOdU5EEImPPFP3bZZ8ay575cdBlzyI+E1GX8SzjG/aMZwv1gsWFytlMMJiTAmOzSLB1mC8b9NKo
WISJ503o35dcie/Epf7RZSrPwmTxKMMjNpMyAq3OwwhVWiruLhArZ89NlzzbVZm/Wyp3txwCsyJY
ujMa9H/vdrRUnVGeFaLb8WUgcBf7AyBaKNFgVaxEkqMe+EZkqAf89zQJY9rKMfb+CMT7w6fOPVvy
vJq299Rp55lML3IRV1P3nzr1Sq5ENe3gqdP+WYQ1Rg8fmZaIfC2ze8+L/RRtJZO59GXkeVo/YsJx
LE0/emS6Xoa6jx/p3jY9HDrowVD8tw//gkspxcpNZuIhB2tTrJrCwjiNRAxSKGaMbfwg/CKXYJKX
oYLxIvsN6eHmM/iTFrMo9NmzGa02NK27P/zA/nvFM8bMYlPwbDCAd7+wH3Zx4F5ruqLp+1vTLxJU
qcw2b9IAVHTL1b2hcNCiECYronHYbJ8Xia9RJBknHJz2+Qvi/8gMwz/P8mWonL8qdsLe/UJEjrd7
Z2XvsLfdC6tDfyLWj3H8nAa9oLn97bkLkU9FthLZ8xf6wV+KoIj0szIPNyIV4EPJoiJIq3bZPhAG
J80z7oNfvvul21ngLvEInTThiMKdCRnKFRiKczUBNmAx3A7o6buHAAfQNCvCKOiMDoZ74PDGNAG/
DwC4eRrCyKHbc3vO6eXk9Wm/BxMWYQ6tvSf+gQkZv4/CGc5xj11sKAx3l2FSPDD0ir4LTrIU2Uw+
uIBxbOAeuMOB09sbqJzP+oOe2z9iO302vZqwV1nI/s4T1h+yfm80HIx6e+xq+g826PUP2cPRwd3B
HqyRLlNY4dAduL2bsyE0fACTJ2mgxdGiw5g7qSwj0EAPET2U8KdQnWfAcMbBLWq6rdqaeu0DfeSA
F/lSZjD9XQfALLqfjDu/GJ2+qyv1CM2jejxuPoLKYZYgEwb+5zxSgMUBWAV4sN52Jef5eb0h5oja
HR9XhShi+YQ4UmM5khz1Mbme3r69vrk8h6a1mKkwR9mWeZ6OdneJggtBG7RxBmFQxqdgnrmqa6He
3DIwd+AMm4oYrwASgN3HNXHYFP2LFKNj1JP0UmcZdNIUwKhlent6c/tm8phS1uu1K0AOJO/m96ib
sYLwnYewN7DJlW4azXXdDFCMpmYuxQIZvZ5fnU3G7Fbw+Nvr6EuMp867512CVkT2FKtRoCFAiGUx
Q0fe1WJpqXYb+gC1/SRvJzV10WPThHruQduE+PoDX/+5uiEWIK7LPPW8K2z7csVoMUq/moocQX7L
sWx7Wy39tvX8FPr3/2F8ScL7MC2WT1MBivpWZlHwUmZoSpWg9daGmC0MlfI+FGeYhLbEbAp00Hz8
UptoPve/WjkVu55Xk/Dpyrrii9B/Ox7UNFU21dW0DzjbUtXPIgEnOweYf9Qgvh45H4hwgKHE8rKN
DY9BJwo0Gf88gfxCUFpWz1Ea7XXRwMzbot2IVbji0eQK0plHhft25l1bCrLrOpNP30TIrUP/9Zvz
mrhl0+eRLgqLaPMnQx3x4HnLIvh6qIvEeygooBoIi92qdHFMfrWbZ0LsxhyKjGy31M7vWL9mAgun
erpRtbXVN/gjPvAlKqk5QcnNUyMkinUahbwukn5uijNopwf/5v5r/jGE/08ZA3GqzeAMS8qnSPsv
cJobseZZUBO51liXe4+4fNly+X9dQUJ0DrV3JFOsUD+RHH07US/Pf/a8is2n2z6Y/gqmZTTNxdrG
jSl//vnl5Z0u5bGerimj1dEqJpq6uF0CQzzCeuWD/N46aCzmeU0+n46Bp5DyTVPYsprJ26amsC38
e3gpABSumhF/sB3x/0A8m+EKMQVpDjwp4CnGIG0ZjJ8S2F7JLD6dXNTksy1tpz74hpb9rRKV9/K9
FIf4x/MM3+WPp2wv8H8roRqqiV82tWx54B41FVAdT3yniucLbMEy7Xk19j9TDbYCXSXObknDZnK3
IhITmeWN45l2T8sdoH7e+9+bEsRPrX5IByHUfgGezNYNpd76/zP1r0n4dGVNww+NCkk/Nw8QtjKE
M55moS+z5Hp+uUkevnna06LvecSV50VfezTQZhitpIjykKqlupFUjW3/aAWMsw/CX06uwPfQnP7G
Y35/9u8/11liZH6NzMP21wX5Ym1Vsu3WCIHSADmnqWyUVGVTO0lu2wzAjnj42MHktztwM8u0PeBT
sGrnuA+bDzaLOC9S0coiqKlZDj+WQ07zjM8BZ5WarL574Wj5errD/yQnq/RVFC6WeeM8rGr9dCbx
0VTik3D53Yz+PVcyWW+SpN/zvJoUT1fIpMjERGSNYFG1NZWx5/bblfPB3qtXvR77LwY1+3uo2S+S
eZiE+Z8cOO80W55XSlL7+RWQQHNNDV3RwfiRgszNCGJamqcrreTiFY/uQyytv4t/VO+hO5VKlOYL
gknJ4Gdt44YngYzHib+ElL0mY7O9fdze/xOOBxocPf2IAF898QyEAoXYxeg9oZtmMhVZHgp8T7Uz
KZ/wbes8XDB84+8lO1Oe0xuyA9bvjwbDUe+QTaa3+ILsyEs0KSdMT/q9PXd44B7tu4dlcwqwe9I/
7g8HXhLzB0e/61Yng56XRAgvDmr7REe0JJZ5cDJ4Obj1kvUS2HciqAxP5HzuJTxJZJH4wlBwuL8M
YT69YtYjoNhaJ05anqqd9GFWFMm1Mye0OJGJHcTxRXmkai2xnOnHBbCDBdwJMDiXGSxYttAqSyjD
IckwT+kqpVlBOJ+HPoTRDa6q35vmMnOUPm5XJ1ZaJURw4vQHveHRcf9o/9i241WWk/Pxq9M3lyC8
NhTn10JkG6JvGjIfxMJn/OGmXClQXHDyA/0BaYtcOoqvBI1ZhWLtBKBADmqDzfGSh5l8cNBoqV/r
Rr8npQaZ4F0NR8ta00yCJ2laO0sRRbRXegWRhfMNQ7InlBxUh3HuJo7QphgiNPPJnApzDwetioFu
WeNtspeBpbHbpVCCWbUxngkG/DGZgFHmS7BDHw2B7s+EiR8VgQjgB9uyZ01tKmOB137ybaoK4neX
SRReIVE2ywS/ZxtZZIYaC+cMdBHOQ1oDNj0Dw4JKhUj/JNYlwd1AzDlsvmJrmfwlZzxNBc8Ybgfe
V/FB0xvkEl+2a+nXS5GwIl1kPAACLpLEv5bgCB/Yzu0yE+AD0AjcRDxZFHyB94YCrT7jYiqE50jC
KuEHUrCefLYUvpGnORV2wIK/SNw1vnQRQchdmS128WkXj2Pu5PzuYnp9dzA8dgZ3OI9UWpIaMQ/g
bOF19GJvl2RGLJcMLx4xkNhcKYJty3iiIp6DFqmbdEv8Ai/wS+S0xYFYhb5gAG1BRJseE2ntg9Wy
BJ3Uo5ZFHki0UH3bC1nS9x+YH0mokixzp2joDKEErziZU2K2Cjn7JzoYDSJXsyfI9VV2pkuYzNGE
lQTGzGJ6B7mhxgoF9glwDhZCgp5OLmAkRIdAq63qclZ4K0EBt5jw6iX0hRJLCy9mIcIwsGYwFuR5
tmHGxGiCQYOyv8Hv2xB0D668YTwIWCaUNkxkF0zxHtjiCoI7JXVgjjOByoF9EL8WPMIdWoQrGLvi
USHYc7MsYP0LIq/XBCQSiOwObPFiIbIR9OvVfyriGWwA+Nyp2iQ+3bPBE23wMlePeAM7Q+ZrxcVx
y0wCvIOtwHjVZQQxzMAoWHSXLstl+u4PKQjiG7bFRQLuhUMM9SlZE8gFPpjJB7oPBaoAscgTkpI9
1LBl6WKOroyD0GW7LMz/AjrMM5oXCIwnZKKt2ew5SIHXpwZaNySJY6QdES3r2BhBso1x679Fcgaq
xoDPdAcYZxzmCBGxWPDZJgfW2FSz1CMmQoVbbmEB5FuHxCKpnyGQa0p2RxRpCd8nwA9GF82QzhwA
xa6pTQLEKsigFxIkkug9qD9aaUGMOsTciPWsMGyHQD0HdOLB/wExMJH6jBAY1f+gECqXKfFhEK7k
y9BTDNwOQzYAU8kVrmtZ6/cGexV35D5vyZYMk+ov34JNP+NqSXyhrzG/gKiWQFRjgu7nIdpIzbc2
ZIyC5Wjx4EP+oiqxjNNf345H7Pb1xZRdXlxd3AL8TS4vxlM2Gd8wyEj/Mb7pMhjEbq9h1Ji9fX19
OWaTm+uz8XTqbvnOJ7QCJUkoKeIjlimU06c4Z5RS4lUftgEgO9CeSWMcwBJhkcrESKggwgRwDiwM
Jf+YAWrDg5Q0ovCJiKmHaeqaCuBXhYcW3PU61wjHmE7QJHd7ApqHqQ5gF6F2waxD6xm51tus55ai
gMWJVFUiD3tGZvXiI2wZDQwrDSx4NgOvcXwZRTpr1hj1qKbJDZElM4uZWYCCMU8KynLq3EAeWIBZ
vuhadN2yS2OYOlrN50BLyxxXrumya51ZaB+AqC+LKCh5CQGO1wmr+Ncuz1JiH2Q96PUqcdnOK4KS
rZBDhqRplNLNMxnb2KVnmxFO3VhbWw0SmR3dtpNHzKttKFObopqr1BT9jW0HRZzq9MimjKbHwR67
b+c4yswgCYhZKwc8QegEGOCPKBrCIARJWGIFBqdUIZS+mK7Ewqa3iGm4WsVW126oDrsmg9Xs0dBP
aQsrQn9ZJPfKsn/GU2wN4yKG3IWustsSBveU6epPM1KpF93HaJQcaNvcIMVPDVO0oIOZdwFReq+2
dedSd7YNXF/7tSvowdalNDUzsCUepTGOD6WqKAU8B34oH4XsDLUILOpsRxNK6e4203O0mJWIMM3o
VQtlF8fBtXwStBhh/WHofprU52wS/5oL57WqBLww0lncjOdQiWNeTZxD8gYWZcIRwZ6uvUyvjkHm
4wfM50ww3Klvme1D2M02OVLvMqdf2029k7S0k1t2ANr3DyyuV9ki1deYpgVaB1ifUE6Ns6HRcOay
1+ECgeYEij7AiLPJmy7DA14YmATrMABHoAzDYGu5gEMLjNhhmd5Wqa8iFdUGu+w0ABBb8mi+CzWt
zsgDAUZtFoNlGR7noL3VnLMWI2vUGnn/+AExD9N6HnU1pOLib8MEiiQQD3BJEM5hxvpmkkxsvluV
qJjS4yS6oYBEizRJHdPQrDPwbyBmxcIahTTxi2GGk5HLmIwC03cMAHhh2i17FdoJ5eTpMnXDJER2
+kZOO8Y6zVueJRg/a7OxhjcREykZIoBGEM1RsGpkzDf4OQIHaAemsiLBL4oQTECwmIAFKNvgqxcE
eRMnnDumtV6rAUj+lfWxRjBpH5aHpAlbGipd6gtbMuq6WRtJv17wKbYLyJYX4DO7C9/aFX4r0ahA
8T8a9ka2spdQQKI125pb2AKSwDHgOWeKr0ocxiMhe26GnTV58JYCwIjgudU1CKiPJ21uTlUQmBzl
QCqFBJByokT6UZgymgvmdQVa9jnaVixXtrrEGGJUqk+bbJ9eUjVAq1oYNwj8LpLgHHQso7SQWLca
IbUB4EkQUUJRayw0oheeAREtBMHQX5YzN2CU+sQo2lQfrJRGoDkOE/xiAJlo4qI9zmsd2AhbqDOy
rlwfWtFgA36FMocHPhDNDf6ZSY6eNGIpWMEqjEwp0HBSPPyF0GRIEoBQNggaQsDIETQGPZO1YcjU
SaHebTwgxB6TCVZm0Oiwubct6qfC5GUz/LSnWvJ5H9DykbW6bAAd/cc6RO67Lwx6K1HnxbjGLVLH
4yO7zwLil14TLVCrjo7tqvO8wMZUTEFMPRGt+UZp+oZSC7107DTRoEIxo15TxCW4H1E7E+naUY0j
1kfPIc0Jw2ksAXfo5IDSHYxCFPCslKgjZFYfsoCf4oPJTtjODSUrtelkVYnQR2ozocnNxBwjFx3b
UmqxtN6iUYCOc7fyHq0HXK7SwxV/YLzNMgjlU8SutqTNbe8j7PIMaAV0XEYIBUyX040JaK6GGizx
uN4p6LunBhT6mNfoTcXjvAYun9OCxtHRvVG7GuTBWvHFCTNCMntaZNMomtRUAdtxwIh32ALKZdVU
VXUsVWnL3VaXCQJrHlJR/WshdGSC3TIUjO9Tj6PCD+AER19JMZVpEZUUzRMmJ1vE8S+5pZPagILO
jyFixOrFEkGCPuYbWRjAk0k6P9DtOr0xdgEs1Q4n6zETfczBI+R2W4merXYI5mEyl/WdB9R09Kl1
NXYp0QSIITeNY0gAyvM2nshkE2PpixEWT359VZMCq3ozgFUDSBoKnnyxyMTCHD2WR7xYEeDXcfdb
ohKfAB/X59cj0I3JG3RFRIC1Frqs4vRpHy6piP2aHNTo1t6gQNbd2AvtD2bPtrUMm61HjGo5jElB
6nGW2mVDkVB1JWhFQfW+vwsImi55F5pBH/iyIa8Sb0gG5iKDUstBHEwwscFhZYJUoDGArDV6zLw9
rSVOBRQbKtdQauHK0NOmoAfYNbZ3Xovb3npIHmoR2eRKSBsn2fwXdxrBG9elJNTMsuflbm0Z09Ve
x6r2MzmZCSR6y7Xb1M7Y7FuFPMytcu1p2tK0EmphyWsqJwNaeLQPZWpAVUM4LylBJQryVOlRI7El
ggas68kMx4vYtkaFSoJjMmQfMcMFXs0GjuxOmk6wajz5HLF3lGVCHO7SUegvljZVobUEqf4ijmTC
w9oM32HR0ZJ9dUolw2MRlZJPCveKKiU6isALTMCyyYoaYpiViQ3zm+FbWAxXJrxWq47Yq8vT29Hg
x8Pu/vFDvzt8GHYHP/Z/DCB90Zj/HL8u8BGZT456Ojzop719yms63Q59Do0q0p96QkxufjmKVtts
AdkSpaJmY+q3J6pfozAXw9Z3qPpb2FrLzIdscdlsw7dtScCzVqv5PyjUm4qsxcc8jOjyR6Mtb30N
u4hbDUtAZX1JDB7eK3O35oAe45l+N9iSDrKogO7111unk8u2WpK8xWG8Ac3Q17jmF8NbW/0BfpbL
HLynsN/b6x3Cz2cXsO+z4fHB8f6eELNB0A+ORXB43BvMjmZcDIaHs8HR4XzQ59DOngHtyZKUNjBf
hKRShQ8thszRJH0MXH4GfSPmkf00qSHlMpYtVSnCfPWITGGzLZf3ItF3OevNb6E4AUSmKzj6DuOG
09t3y/SHMNUXpvfdfuf33/8H4iBpAg==
===END CRASH DUMP===

**Comment by falkirks** [comment]
If you have other errors just post them here or you are welcome to fix it yourself and PR

**Comment by Subject-4** [comment]
Okay, thanks
