### ISSUE TITLE
Can you update this to the latest version 3.0.0-ALPHA11

### ISSUE THREAD

**Issue by brexmania123** [Falkirks/iControlU#6]
Can you update this to the latest version 3.0.0-ALPHA11
Can you update this to the latest version 3.0.0-ALPHA11
Can you update this to the latest version 3.0.0-ALPHA11
Can you update this to the latest version 3.0.0-ALPHA11
Can you update this to the latest version 3.0.0-ALPHA11
Can you update this to the latest version 3.0.0-ALPHA11
Can you update this to the latest version 3.0.0-ALPHA11
Can you update this to the latest version 3.0.0-ALPHA11

**Comment by falkirks** [comment]
Duplicate of #2
