### ISSUE TITLE
Please update.

### ISSUE THREAD

**Issue by t0mtee** [Falkirks/iControlU#7]
Hello,

Back in the good ol' days, I loved this plugin. Now, I can't use it. I have found out it is because it hasn't been updated to the latest API, and I don't know PHP, so I can't recreate it. Please update it, this is one of my favourite plugins.

**Comment by iZeaoGamer** [comment]
He's not going to update, As far as I know, he's stopped updating it a while ago however, I could try updating it if you want me to?

**Comment by falkirks** [comment]
@iZeaoGamer You are welcome to update and PR if you like.

**Comment by t0mtee** [comment]
@iZeaoGamer Yeah please, if you know how.

**Comment by iZeaoGamer** [comment]
I've made a PR, check it out.
